version: '3.0'

services:
  trading-robot:
    image: registry.gitlab.com/horman-trading-platform/trading-robot:latest
    restart: always
    environment:
      - DEPLOY_ENV=$DEPLOY_ENV
      - HTTP_API_PORT=$HTTP_API_PORT

      - POLONIEX_API_KEY=$POLONIEX_API_KEY
      - POLONIEX_API_SECRET=$POLONIEX_API_SECRET

      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "${HTTP_API_PORT}:${HTTP_API_PORT}/tcp"
    networks:
      - backend
    logging:
      driver: local
      options:
        max-size: "250mb"

networks:
  backend:

