image: scratch

stages:
  - build
  - package
  - deploy

build:
  image: bellsoft/liberica-openjdk-alpine:15
  stage: build
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew bootJar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  interruptible: true
  retry: 1
  only:
    - master

package:
  image: docker:19.03.8
  stage: package
  variables:
    DOCKER_CLI_EXPERIMENTAL: enabled
    BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
    BUILD_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
  services:
    - name: docker:19.03.8-dind
      command: ["--experimental"]
  before_script:
    - mkdir -p ~/.docker/cli-plugins/
    - wget -O ~/.docker/cli-plugins/docker-buildx $BUILDX_URL
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use --name mybuilder
    - docker buildx build --platform $BUILD_PLATFORMS --push -t $CI_REGISTRY_IMAGE .
  interruptible: true
  retry: 1
  only:
    - master

deploy:
  image: debian
  stage: deploy
  before_script:
    - mkdir ~/.ssh
    - cp $DEPLOY_SERVER_SSH_PRIVATE_KEY ~/.ssh/id_rsa
    - cp $DEPLOY_SERVER_SSH_KNOWN_HOSTS ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
    - chmod 600 ~/.ssh/id_rsa
    - chmod 644 ~/.ssh/known_hosts
    - apt-get -qq update && apt-get install netcat-openbsd openssh-client tor -y -qq > /dev/null
    - tor --runasdaemon 1
    - while ! nc -z localhost 9050; do sleep 0.1; done
  script:
    - |
      ssh -o ProxyCommand='nc -X 5 -x localhost:9050 %h %p' \
      $DEPLOY_SERVER_SSH_USER@$DEPLOY_SERVER_SSH_SERVER "
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
      docker-compose down &&
      docker-compose pull &&
      docker-compose up -d &&
      docker logout $CI_REGISTRY
      "
  only:
    - master
  when: manual
  retry: 1
