server:
  port: ${HTTP_API_PORT}
  error:
    whitelabel:
      enabled: false

spring:
  main:
    banner-mode: "off"
    lazy-initialization: false
  output:
    ansi:
      enabled: always
  devtools:
    livereload:
      enabled: true
  rsocket:
    server:
      mapping-path: /api
      port: ${RSOCKET_PORT}