server:
  address: 0.0.0.0
  port: ${HTTP_API_PORT:8080}
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: ${DEPLOY_ENV:dev}
  main:
    banner-mode: "off"
    lazy-initialization: false
    web-application-type: reactive
  output:
    ansi:
      enabled: always
logging:
  pattern:
    console: "%clr(%date{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5level) %clr(--){faint} %clr([%thread]){faint} %clr(%.40logger{39}){cyan} %clr(:){faint} %msg%n%wEx"
