server:
  port: ${PORT}
  error:
    whitelabel:
      enabled: false

spring:
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: always
  devtools:
    livereload:
      enabled: true
